@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant TaskListView as UI
participant TaskListController
participant TaskAddController
participant TaskService
participant Server
participant TaskManager
participant Task

User -> UI: Clicks Add Task
UI -> TaskListController: handleAddTask()
TaskListController -> TaskAddController: switchScene()
TaskAddController -> TaskService: addTask()
TaskService -> Server: addTask()
Server -> TaskManager: addTask()
TaskManager -> Task: new Task()
Task --> TaskManager: Task
TaskManager --> Server: Task
Server --> TaskService: Task
TaskService --> TaskAddController: Task
TaskAddController --> TaskListController: switchScene()
TaskListController -> UI: handleRefreshTaskList()

@enduml