@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant TaskEditView as UI
participant TaskListView
participant TaskListController
participant TaskEditController
participant TaskService
participant Server
participant TaskMana

User -> UI: Update Task
UI -> TaskEditController: handleUpdateTask()
TaskEditController -> TaskService: updateTask()
TaskService -> Server: updateTask()
Server -> TaskManager: updateTask()
TaskManager -> TaskManager: HashMap.put()
TaskManager --> Server: Task
Server --> TaskService: Task
TaskService --> TaskEditController: Task
TaskEditController --> TaskListController: switchScene()
TaskListController --> TaskListView: handleRefreshTaskList()

@enduml