@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant TaskEditView as UI
participant TaskListView
participant TaskListController
participant TaskEditController
participant TaskService
participant Server
participant TaskManager
participant Task

User -> UI: Delete Task
UI -> TaskEditController: handleDeleteTask()
TaskEditController -> TaskService: deleteTask()
TaskService -> Server: deleteTask()
Server -> TaskManager: deleteTask()
TaskManager -> TaskManager: HashMap.remove()
TaskManager --> Server: boolean
Server --> TaskService: boolean
TaskService --> TaskEditController: boolean
TaskEditController --> TaskListController: switchScene()
TaskListController --> TaskListView: handleRefreshTaskList()

@enduml